[build]
publish = "build/web"
command = "git clone https://github.com/flutter/flutter.git --depth 1 -b stable _flutter && ./_flutter/bin/flutter build web --release --no-tree-shake-icons"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200